### ISSUE TITLE
Authentication without SSL certificate validation

### ISSUE THREAD

**Issue by pkleanthous** [ramonvanalteren/jenkinsapi#9]
Hello the Jenkins server is using https. Unfortunately I can't use the lib as it is.
Inside the libraries that Jenkinsapi use there is an option Check_SSL="True".
Can somehow expose this to your api ? 

> > > import jenkinsapi
> > > print(jenkinsapi.**version**)
> > > 0.2.26
> > > 
> > > from jenkinsapi.jenkins import Jenkins
> > > J = Jenkins(baseurl='https://myurl')
> > > Traceback (most recent call last):
> > > File "<input>", line 1, in <module>
> > > File "/usr/local/lib/python2.7/dist-packages/jenkinsapi/jenkins.py", line 51, in **init**
> > > JenkinsBase.**init**(self, baseurl, poll=not lazy)
> > > File "/usr/local/lib/python2.7/dist-packages/jenkinsapi/jenkinsbase.py", line 34, in **init**
> > > self.poll()
> > > File "/usr/local/lib/python2.7/dist-packages/jenkinsapi/jenkinsbase.py", line 57, in poll
> > > data = self._poll(tree=tree)
> > > File "/usr/local/lib/python2.7/dist-packages/jenkinsapi/jenkinsbase.py", line 67, in _poll
> > > return self.get_data(url, tree=tree)
> > > File "/usr/local/lib/python2.7/dist-packages/jenkinsapi/jenkinsbase.py", line 77, in get_data
> > > response = requester.get_url(url, params)
> > > File "/usr/local/lib/python2.7/dist-packages/jenkinsapi/utils/requester.py", line 95, in get_url
> > > return requests.get(self._update_url_scheme(url), *_requestKwargs)
> > > File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
> > > return request('get', url, *_kwargs)
> > > File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
> > > return session.request(method=method, url=url, *_kwargs)
> > > File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 456, in request
> > > resp = self.send(prep, *_send_kwargs)
> > > File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 559, in send
> > > r = adapter.send(request, **kwargs)
> > > File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 382, in send
> > > raise SSLError(e, request=request)
> > > SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

**Comment by AngelM1981** [comment]
You can use ssl_verify=False as ma,ed c'tor parameter.
